skip to install grcov
SpringQL/SpringQL pull request #111
Opened 2022-04-20 00:18 UTC by kazuk

Close #110 

 add SKIP_INSTALL_GRCOV environment variable.

2022-04-20 03:53 UTC, kazuk commented
`install_grcov` was gone!

```
[cargo-make] INFO - Running Task: lcov
[cargo-make] INFO - ==================Time Summary==================
[cargo-make] INFO - coverage_grcov_run_test_stable:   52.39%     163.97 seconds
[cargo-make] INFO - coverage_grcov_build_stable:      40.79%     127.65 seconds
[cargo-make] INFO - coverage_grcov_stable:            5.52%      17.28 seconds
[cargo-make] INFO - [Setup Env]:                      1.29%      4.05 seconds
[cargo-make] INFO - coverage_grcov_prepare_outdir:    0.01%      0.03 seconds
[cargo-make] INFO - [Load Makefiles]:                 0.00%      0.00 seconds
[cargo-make] INFO - lcov:                             0.00%      0.00 seconds
[cargo-make] INFO - ================================================
[cargo-make] INFO - Build Done in 313.53 seconds.
```

2022-04-20 05:25 UTC, laysakura requested changes

2022-04-20 05:25 UTC, laysakura commented on Makefile.toml
> +SKIP_INSTALL_GRCOV = 1
[IMO] 範囲が広く感じるので、 `alias="coverage_grcov"` にだけ適用されるような書き方になるとありがたいです。

cargo-make 的に無理あるならこのままでokです。

2022-04-20 05:29 UTC, kazuk commented on Makefile.toml
> +SKIP_INSTALL_GRCOV = 1
それを当初指定したのですが、手元ではOK、github actions ではNGになったんですよね。

https://github.com/SpringQL/SpringQL/pull/111/commits/13968a0f7c71452a92fa2d0ca1a5d48bf972968e

github actions 側はデバッグがしづらくスコープが広がってます。

2022-04-20 05:34 UTC, laysakura commented on Makefile.toml
> +SKIP_INSTALL_GRCOV = 1
承知です。そしたらこれでLGTM

2022-04-20 05:34 UTC, laysakura approved these changes

2022-04-20 05:35 UTC, laysakura commented
[slack notification job is failing](https://github.com/SpringQL/SpringQL/runs/6088845525?check_suite_focus=true) but it's irrelevant to this PR.

Fix later.

2022-04-20 05:35 UTC, merged

2022-04-20 05:36 UTC, laysakura commented on Makefile.toml
> +SKIP_INSTALL_GRCOV = 1
(Sorry, I started comments in Japanese... We should use English in GitHub)

2022-04-23 00:14 UTC, kazuk commented on Makefile.toml
> +SKIP_INSTALL_GRCOV = 1
TODO: try with cargo-make 0.35.11

cargo-make 0.35.11 contains enhancement relating Environment Variable with Condition.
 https://github.com/sagiegurari/cargo-make/issues/648