Refactor_api_2
SpringQL/SpringQL pull request #169
Opened 2022-05-31 22:53 UTC by kazuk

## Issue number and link

Fixes: #xxx

## Describe your changes

## Checklist before requesting a review

- [ ] I follow the [Semantic Pull Requests](https://github.com/zeke/semantic-pull-requests) rules (bugfix/feature)
- [ ] I specified links to related issues (must: bugfix, want: feature)
- [ ] I have performed a self-review of my code (bugfix/feature)
- [ ] I have added thorough tests (bugfix/feature)
- [ ] I have edited `## [Unreleased]` section in `CHANGELOG.md` following [keep a changelog](https://keepachangelog.com/en/1.0.0/) syntax (bugfix/feature)
- [ ] I {made/will make} a related pull request for [documentation repo](https://github.com/SpringQL/SpringQL.github.io) (feature)

2022-06-05 23:27 UTC, kazuk commented on springql-core/src/lib.md
> +#   return ();
fix: https://github.com/SpringQL/SpringQL/issues/168

2022-06-07 00:37 UTC, laysakura requested changes
I appreciate your diligent work!

Just one thing: I would like to totally remove "high-level" and "low-level" category from APIs and documentations.

I guess we can remove `low_level` mod in springql-core crate in this PR.

2022-06-07 00:37 UTC, laysakura commented on springql-core/src/api/low_level_rs/spring_config.rs
>  pub fn spring_config_toml(overwrite_config_toml: &str) -> Result<SpringConfig> {
I guess we can remove this function (and write wrapper codes calling `SpringConfig::new(overwrite_config_toml)` in SpringQL-client-c/src/lib.rs ).

2022-06-07 00:37 UTC, laysakura commented on springql-core/src/api/low_level_rs/engine_mutex.rs
>  // This file is part of https://github.com/SpringQL/SpringQL which is licensed under MIT OR Apache-2.0. See file LICENSE-MIT or LICENSE-APACHE for full license details.
Remove this file.

2022-06-07 00:37 UTC, laysakura commented on springql-core/src/api/low_level_rs.rs
> +pub mod spring_config;
We maybe able to totally remove this `low_level_rs` mod.

And then, we won't need to say "high-level" nor "low-level" anywhere.

2022-06-08 00:56 UTC, laysakura approved these changes
👏

2022-06-08 00:56 UTC, merged